feat: customize name of secret
ory/hydra-maester pull request #125
Opened 2023-07-07 14:48 UTC by TartanLeGrand

## Proposed changes

This pull request introduces the ability to customize `ClientIDKey` and `ClientSecretKey` variables. These variables can now be modified by setting the environment variables `CLIENT_ID_KEY` and `CLIENT_SECRET_KEY` respectively. If these environment variables are not set, the default values (currently "CLIENT_ID" for `ClientIDKey` and "CLIENT_SECRET" for `ClientSecretKey`) will be used.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security vulnerability, I confirm that I got approval from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

## Further comments

In this pull request, I have modified `ClientIDKey` and `ClientSecretKey` to be configurable via environment variables. This allows for greater flexibility in configuring the system, while maintaining sensible defaults.

2023-07-07 14:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/hydra-maester?pullRequest=125) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/hydra-maester?pullRequest=125) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/hydra-maester?pullRequest=125) it.</sub>

2023-07-20 12:15 UTC, TartanLeGrand commented
@Demonsthere can you review this ? :smiley:

2023-07-24 07:01 UTC, Demonsthere commented on controllers/oauth2client_controller.go
> +	ClientIDKey     = DefaultClientID
The idea is pretty simple and I see no reason to why not merge it, but need one little thing first ;) As we're adding new config options, with Envs, please update the README accordingly!

2023-07-24 07:02 UTC, Demonsthere requested changes
Please update readme then we can merge :wink:

2023-10-24 08:18 UTC, Demonsthere approved these changes

2023-10-24 08:18 UTC, merged

2024-12-12 10:50 UTC, ariep commented
> Hmm, here the default values went from lowercase to uppercase.... So it kinda broke existing crds

Indeed. We were content with the old fixed (lowercase) keys, but now have to set these new env vars to keep existing setups from breaking.